### ISSUE TITLE
AttributeError: 'FPDF' object has no attribute 'close'

### ISSUE THREAD

**Issue by carlosal1015** [ismet55555/exam-terminal#73]
**Describe the bug**
After close quiz and save a PDF, throws this error.
```
/usr/bin/exam-terminal:8: DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6
  sys.exit(main())
/usr/bin/exam-terminal:8: DeprecationWarning: "dest" parameter is deprecated since v2.2.0, unused and will soon be removed
  sys.exit(main())
Traceback (most recent call last):
  File "/usr/bin/exam-terminal", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/exam_terminal/__main__.py", line 97, in main
    exitcode = exam_terminal.exam_terminal(exam_file_contents)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/exam_terminal/exam_terminal.py", line 45, in exam_terminal
    exam.export_results_to_pdf()
  File "/usr/lib/python3.11/site-packages/exam_terminal/ExamTerminal.py", line 1183, in export_results_to_pdf
    pdf.close()
    ^^^^^^^^^
AttributeError: 'FPDF' object has no attribute 'close'
```

python 3.11.6
click 8.1.7
fpdf2 2.7.7
pyaml 23.9.0
requests 2.31.0

**Expected behavior**
Create a PDF.

**Comment by ismet55555** [comment]
Thank you for reporting this! Let me investigate.

**Comment by carlosal1015** [comment]
Many thanks for the help, I test last version and works fine.
